### ISSUE TITLE
Having a problem launching editor

### ISSUE THREAD

**Issue by Dano25655** [KarlitosVII/trilogy-save-editor#25] opened 2021-06-22 08:59 UTC
Just downloaded the editor, when i try launching it gives me this then crashes
![Shit Dude](https://user-images.githubusercontent.com/86291420/122896346-d65e5f80-d2fd-11eb-8e2d-ae021ac76004.png)

**Comment by mirh** [comment] 2021-06-22 09:30
Duplicate of #20

**Comment by KarlitosVII** [comment] 2021-06-22 13:34
Does using directly --dx11 or --dx12 works ?

**Comment by Dano25655** [comment] 2021-06-22 14:06
No it does not

**Closed** 2021-07-03 09:20 UTC
Labels: bug
